# Generated by Django 5.2.3 on 2025-06-28 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_remove_article_alerte_envoyee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='quantite',
        ),
        migrations.AlterField(
            model_name='article',
            name='alerte_stock_faible_envoyee',
            field=models.BooleanField(default=False, help_text="Passé à True dès qu'une alerte stock < stock_min a été envoyée"),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock actuel'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
