# Generated by Django 5.2.3 on 2025-06-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_remove_article_quantite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='stock_min',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='Seuil minimal pour alerte (optionnel)', null=True),
        ),
    ]
