# Generated by Django 5.2.3 on 2025-06-28 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_alter_article_stock_min'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='facteur_co2',
            field=models.FloatField(blank=True, default=0.0, null=True, verbose_name='Facteur CO₂ (kg/unité)'),
        ),
    ]
