# Generated by Django 5.2.3 on 2025-06-28 14:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_article_facteur_co2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='alerte_stock_faible_envoyee',
        ),
        migrations.AddField(
            model_name='article',
            name='derniere_entree',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='derniere_sortie',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='user_derniere_entree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dernieres_entrees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='article',
            name='user_derniere_sortie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dernieres_sorties', to=settings.AUTH_USER_MODEL),
        ),
    ]
