# Generated by Django 5.2.3 on 2025-06-28 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_simplify_stock_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='derniere_entree',
        ),
        migrations.RemoveField(
            model_name='article',
            name='derniere_sortie',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user_derniere_entree',
        ),
        migrations.RemoveField(
            model_name='article',
            name='user_derniere_sortie',
        ),
        migrations.AddField(
            model_name='article',
            name='alerte_stock_faible_envoyee',
            field=models.BooleanField(default=False, help_text="Passé à True dès qu'une alerte stock < 10 a été envoyée"),
        ),
        migrations.AddField(
            model_name='article',
            name='quantite',
            field=models.IntegerField(default=0, help_text='Quantité initiale'),
        ),
        migrations.AlterField(
            model_name='article',
            name='facteur_co2',
            field=models.FloatField(default=0.0, verbose_name='Facteur CO₂ (kg/unité)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock',
            field=models.IntegerField(default=0, help_text='Stock courant'),
        ),
        migrations.AlterField(
            model_name='article',
            name='stock_min',
            field=models.PositiveIntegerField(default=1, help_text='Seuil minimal pour alerte'),
        ),
    ]
