# Generated by Django 5.2.3 on 2025-07-02 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_article_derniere_entree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandearticle',
            name='gestionnaire',
            field=models.ForeignKey(default=1, limit_choices_to={'role': 'gestionnaire'}, on_delete=django.db.models.deletion.CASCADE, related_name='demandes_reçues', to=settings.AUTH_USER_MODEL, verbose_name='Gestionnaire destinataire'),
            preserve_default=False,
        ),
    ]
