# Generated by Django 5.2.3 on 2025-07-02 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_demandearticle_gestionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandearticle',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
